// <auto-generated/>
using ApiSdk.Sample1.Sample2;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Sample1
{
    /// <summary>
    /// Builds and executes requests for operations under \sample1
    /// </summary>
    public class Sample1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sample2 property</summary>
        public ApiSdk.Sample1.Sample2.Sample2RequestBuilder Sample2
        {
            get => new ApiSdk.Sample1.Sample2.Sample2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Sample1.Sample1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sample1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sample1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Sample1.Sample1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sample1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sample1", rawUrl)
        {
        }
    }
}
